### PR TITLE
Update Elegoo.ini

### PR DESCRIPTION
**Pull request by mlee12382**
Added Thumbnails and fixed a couple 2D issues and added BLTouch gcode that has been commented out for easy implementation.

### CODE REVIEW

**Comment by mlee12382** [comment]
I think this should fix it. :) It will be nice to have an easier way to get people setup for PrusaSlicer/SuperSlicer :)

**Comment by andrewsuzuki** [comment]
Sweet. Though changing the two gcode lines in \*common\* affects the single-extruder printers too, so perhaps put them at the end of the \*dualextruder\* instead (which the 2D inherits from)?

**Comment by mlee12382** [comment]
Right.. since the 2D inherits the gcode from the 2 how would we change that? Does it overwrite or amend if you add it specifically to the 2D sub settings?

**Comment by andrewsuzuki** [comment]
You can add it to `[printer:*dualextruder*]`, the second to last section. The 2D inherits from both dualextruder and the 2.

It will overwrite it. Which is an annoying limitation of the .ini format as opposed to some sort of DSL, but it works.

**Comment by mlee12382** [comment]
Also having it retract at the end of the print is sometimes a good thing even for single extruder, and it loads back in in the start code so that's not necessarily breaking anything having it there. I can return the original and put it specifically in the dualextruder section though.

**Comment by mlee12382** [comment]
Ok, I updated it, Hopefully that will work better.

**Comment by andrewsuzuki** [comment]
Hmm, fair. Let's do parity for now and I'll test that out later. Thanks for the help!

Closes #1

**Pull request merged**
